const languageSettings = {

    English: {

    languageText: "ENGLISH",
    SignIn: "Sign In",
    SignOut: "Sign Out",
    SignWith: "or sign in with:",
    SButton: "LOGIN",
    Email: "Email address",
    Password: "Password",
    forgot: "Forgot Password?",
    bottomLine: "Don’t have an account? Sign up",
    here:"here! ",
    SignUp: "Sign Up",
    forget: "Forgot password?",
    resetPassword: "RESET PASSWORD",
    otp: "Enter OTP",
    otpMessage: "We send you an email with a One Time Password.",
    otpMessagecntd: "Please enter the code below",
    timeleft: "seconds left",
    start: "START NOW!",
    contactSupport: "Contact support",
    oldPassword:"Old Password",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    changePassword: "Change password",
    changeLanguage: "Change Language",
    profile: "Profile",
    firstName: "First name",
    lastName: "Last name",  
    Phone: "Phone number",
    ready: "I’M READY!",
    money: "PUSH TO EARN MONEY!",
    workButton: "HOW DOES IT WORK?",
    myProfile: "My profile",
    cardDetails: "Bank account",
    add: "Add your bank account details here",
    editProfile: "Edit profile",
    BankName: "Bank name:",
    Iban: "IBAN number:",
    Bic: "BIC number:",
    bankbutton: "SAVE",
    friends: "Candidate",
    status: {
        wc: 'Waiting Contract',
        ar: 'Archived',
        vd: 'Validating',
        pd: 'Pending'
    },
    loginSuccessfull:{
        ls: 'Login Successfull!',
        pg: 'Push To Earn Money Page'
    },
    addFriends: "You don’t have any candidates yet. Add a friend and earn money while you sleep!",
    addFriendsButton: "ADD CANDIDATE",
    addFriendNew: "Add candidate",
    addFriendPhoneButton: "SEARCH PHONE CONTACT",
    addFriendName: "First + last name", 
    friend: "Candidates",
    agree:"I Agree",
    disagree: "I Disagree",
    Name: "Name",
    pending: "Pending",
    wApproval: "Waiting approval",
    onContract: "On Contract",
    sick: "Sick",
    rejected: "Rejected",
    Money: "MONEY",
    nothing:"NO RECORDS TO SHOW!",
    pPolicy: "Private Policy",
    backOverview : "Back to overview",
    Total: "Total Hours Worked",
    TotalNext: "Total Earned",
    payed: "Payed",
    Information: "Information",
    Support: "Support",
    faq: "FAQ",
    },
    
    Dutch: {

    languageText: "NEDERLANDS",
    SignIn: "Log in",
    SignOut: "Sign Out",
    SignWith: "of log in met:",
    SButton: "INLOGGEN",  
    Email: "Email adres", 
    Password: "Wachtwoord",
    forgot: "Wachtwoord vergeten?",
    bottomLine: "Nog geen profiel? ",
    here:"Hier inschrijven!",
    SignUp: "Inschrijven",
    forget: "Wachtwoord vergeten",
    resetPassword: "RESET WACHTWOORD",
    otp: "OTP ingeven",
    otpMessage: "We hebben jou een email gestuurd met een One Time Password.",
    otpMessagecntd:"Voeg hieronder code toe",
    timeleft: "seconden over",
    start: "START NU!",
    contactSupport: "Contacteer support",
    oldPassword: "Oud wachtwoord",
    newPassword: "Nieuw wachtwoord",
    confirmPassword: "Herhaal nieuw wachtwoord",
    changePassword: "Wachtwoord wijizigen",
    changeLanguage: "Taal Wijzigen",
    profile: "Profiel",
    firstName: "Voornaam",
    lastName: "Naam",
    cancel:'Annuleer',
    confirm: 'Bevestigen',
    Phone: "Telefoonnummer",
    ready: "KLAAR!",
    money: "PUSH TO EARN MONEY!",
    workButton: "HOE WERKT HET?",
    myProfile: "Mijn profiel",
    cardDetails: "Bankgegevens",
    add: "Voeg je bankgegevens hier toe",
    editProfile: "Taal wijzigen",
    BankName: "Naam bank",
    Iban: "IBAN nummer",
    Bic: "BIC nummer",
    bankbutton: "OPSLAAN",
    friends: "Kandidaten!",
    status: {
        wc: 'Waiting Contract',
        ar: 'Archived',
        vd: 'Validating',
        pd: 'Pending'
    },
    loginSuccessfull:{
        ls: 'Login Successfull!',
        pg: 'Push To Earn Money Page'
    },
    addFriends: "Je hebt nog geen kandidaten.Voeg een kandidaat toe en verdien al slapend geld!",
    addFriendsButton: "VOEG EEN KANDIDAAT TOE",
    addFriendNew: "Kandidaat Toevoegen",
    addFriendPhoneButton: "ZOEK IN JE TELEFOONBOEK",
    addFriendName: "Voornaam + Naam",
    friend: "kandidaat",
    agree:"I Agree",
    disagree: "I Disagree",
    Name: "Naam",
    pPolicy: "Private Policy",
    pending: "In afwachting",
    wApproval: "Wachtend op goedkeuring",
    onContract: "Onder contract",
    sick: "Ziek",
    rejected: "Afgekeurd",
    Money: "GELD",
    nothing:"Geen records!",
    backOverview : "terug naar overzicht",
    Total: "Total gewerkte uren",
    TotalNext: "Totaal verdiend",
    payed: "betaald",
    Information: "Informatie",
    Support: "Support",
    faq: "FAQ",
    
    },
    
    French: {

    languageText: "FRANÇAIS",
    SignIn: "Se connecter",
    SignOut: "Sign Out",
    SignWith: "ou connectez-vous avec:",
    SButton: "LOGIN",
    Email: "Adresse e-mail",    
    Password: "Mot de passe",    
    forgot: "Mot de passe oublié?",    
    bottomLine: "Vous n'avez pas de compte? Inscrivez-vous",
    here:"ici!",
    SignUp: "S'inscrire",
    forget: "Mot de passe oublié",    
    resetPassword: "RÉINITIALISER",
    otp: "Entrer OTP",    
    otpMessage: "Nous vous envoyons un email avec un mot de passe unique(OTP).",
    otpMessagecntd:"Veuillez entrer le code ci-dessous",
    timeleft: "secondes restantes",
    start: "COMMENCEZ!",
    cancel:'Annuler',
    confirm: 'Confirmer',
    contactSupport: "Contact support",
    oldPassword: "Ancien mot de passe",    
    newPassword: "Nouveau mot de passe",    
    confirmPassword: "Répéter",    
    changePassword: "Changer",    
    changeLanguage: "Changer de langue",
    profile: "Profil",    
    firstName: "Prénom",    
    lastName: "Nom de famille",    
    Phone: "Numéro de téléphone",    
    ready: "PRÊT!",    
    money: "PUSH TO EARN MONEY!",    
    workButton: "COMMENT",    
    myProfile: "Mon profil",
    cardDetails: "Coordonnées bancaires",    
    add: "Ajoutez vos coordonnées bancaires ici",
    editProfile: "Changer profil",    
    BankName: "Nom de la banque",
    Iban: "Numéro IBAN",
    Bic: "Numéro BIC",
    bankbutton: "ENREGISTRER",
    friends: "Candidats",
    agree:"I Agree",
    disagree: "I Disagree",
    addFriends: "Vous n'avez pas encore de candidats. Ajoutez un candidat et gagnez de l'argent!",
    addFriendsButton: "AJOUTEZ",
    addFriendNew: "Ajoutez un candidat",
    addFriendPhoneButton: "RECHERCHER",
    addFriendName: "Prénom + Nom",
    friend: "Candidat",
    status: {
        wc: 'Waiting Contract',
        ar: 'Archived',
        vd: 'Validating',
        pd: 'Pending'
    },
    loginSuccessfull:{
        ls: 'Login Successfull!',
        pg: 'Push To Earn Money Page'
    },
    pPolicy: "Private Policy",
    Name: "Nom",
    pending: "En attendant",
    wApproval: "En attente d'approbation",    
    onContract: "Sur contract",    
    sick: "Malade",
    rejected: "Rejeté",
    Money: "ARGENT",
    nothing:"Pas d'enregistrements!",
    backOverview : "Retour à l'aperçu",
    Total: "Nombre total d'heures travaillées",
    TotalNext: "Totalement gagné",
    payed: "Payé",
    Information: "Information",
    Support: "Support",
    faq: "QFP",
    
    }
    
    }

    export default languageSettings;