const languageSettings = {

    English: {

    languageText: "ENGLISH",
    SignIn: "Sign In",
    SignOut: "Sign Out",
    SignWith: "or sign in with:",
    SignUpWith: "or sign up with:",
    SButton: "LOGIN",
    Email: "Email address",
    Password: "Password",
    forgot: "Forgot Password?",
    bottomLine: "Don’t have an account? Sign up",
    here:"here! ",
    SignUp: "Sign Up",
    saveData: "Save Data",
    forget: "Forgot password?",
    resetPassword: "RESET PASSWORD",
    otp: "Enter OTP",
    otpMessage: "We send you an email with a One Time Password.",
    otpMessagecntd: "Please enter the code below",
    otpSent: "OTP verzonden met succes naar uw mobiele nummer",
    otpError:'OTP is incorrect',
    timeleft: "seconds left",
    start: "START NOW!",
    contactSupport: "Contact support",
    oldPassword:"Old Password",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    changePassword: "Change password",
    changeLanguage: "Change Language",
    profile: "Profile",
    firstName: "First name",
    lastName: "Last name",  
    Phone: "Phone number",
    PushForJob: "PushForJob",
    FNameErrorText: "First Name is not valid",
    LNameErrorText: "Last Name is not valid",
    TelephoneNumberError: "Phone number is not valid",
    EmptyErrorText: "All fields are required!",
    ready: "I’M READY!",
    money: "PUSH TO EARN MONEY!",
    workButton: "HOW DOES IT WORK?",
    myProfile: "My profile",
    cardDetails: "Bank account",
    add: "Add your bank account details ",
    editProfile: "Edit profile",
    BankName: "Bank name:",
    Iban: "IBAN number:",
    Bic: "BIC number:",
    bankbutton: "SAVE",
    friends: "Candidates",
    status: {
        wc: 'Waiting Contract',
        ar: 'Archived',
        vd: 'Validating',
        pd: 'Pending'
    },
    loginSuccessfull:{
        ls: 'Login Successfull!',
        pg: 'Push To Earn Money Page'
    },
    addFriends: "You don’t have any candidates yet. Add a friend and earn money while you sleep!",
    addFriendsButton: "Add Candidate",
    addFriendNew: "Add candidate",
    addFriendPhoneButton: "Search Phone Contact",
    addFriendName: "First + last name", 
    FNameErrorText: "Voornaam niet correct",
    LNameErrorText: "Naam niet correct",
    TelephoneNumberError: "Telefoonnummer niet correct",
    EmptyErrorText: "Alle velden zijn verplicht!",
    friend: "Candidate",
    agree:"I Agree",
    disagree: "I Disagree",
    Name: "Name",
    pending: "Pending",
    wApproval: "Waiting approval",
    onContract: "On Contract",
    sick: "Sick",
    rejected: "Rejected",
    Money: "MONEY",
    nothing:"NO RECORDS TO SHOW!",
    pPolicy: "Private Policy",
    backOverview : "Back to overview",
    Total: "Total Hours Worked",
    TotalNext: "Total Earned",
    payed: "Payed",
    partial: "Partial",
    AdjustmentContract: 'Adjustment Contract',
    Correction: 'Correction',
    Time:'Time',
    NewTime: 'New Time',
    Information: "Information",
    Support: "Support",
    faq: "FAQ",
    duplicateMobilePhone:'Duplicate Mobile Phone Number already exists',
    invalidMobilePhone:'Mobile Number not valid',
    one: "JANUARY",
    two: "FEBRUARY",
    three: "MARCH",
    four: "APRIL",
    five: "MAY",
    six: "JUNE",
    seven: "JULY", 
    eight: "AUGUST",
    nine: "SEPTEMBER",
    ten: "OCTOBER",
    eleven: "NOVEMBER",
    twelve: "DECEMBER",
    resend: "Re-send",    
    //Redux Translations
    completeProfile: 'Please Complete your Profile!',
    signUpText: 'Please Sign Up , as your phone number does not exist in our database'
    },
    
    Dutch: {

    languageText: "NEDERLANDS",
    SignIn: "Log in",
    SignOut: "Sign Out",
    SignWith: "of log in met:",
    SignUpWith: "of Inschrijven met:",
    SButton: "INLOGGEN",  
    Email: "Email adres", 
    Password: "Wachtwoord",
    forgot: "Wachtwoord vergeten?",
    bottomLine: "Nog geen profiel? ",
    here:"Hier inschrijven!",
    SignUp: "Inschrijven",
    forget: "Wachtwoord vergeten",
    resetPassword: "RESET WACHTWOORD",
    saveData: "gegevens opslaan",
    otp: "OTP ingeven",
    otpMessage: "We hebben jou een email gestuurd met een One Time Password.",
    otpMessagecntd:"Voeg hieronder code toe",
    otpSent: "OTP sent Successfully to Your Mobile Number",
    otpError:'OTP is onjuist',
    timeleft: "seconden over",
    start: "Begin NU!",
    contactSupport: "Contacteer support",
    oldPassword: "Oud wachtwoord",
    newPassword: "Nieuw wachtwoord",
    confirmPassword: "Herhaal nieuw wachtwoord",
    changePassword: "Wachtwoord wijizigen",
    changeLanguage: "Taal Wijzigen",
    profile: "Profiel",
    firstName: "Voornaam",
    lastName: "Naam",
    cancel:'Annuleer',
    confirm: 'Bevestigen',
    Phone: "Telefoonnummer",
    PushForJob: "PushForJob",
    FNameErrorText: "Voornaam niet correct",
    LNameErrorText: "Naam niet correct",
    TelephoneNumberError: "Telefoonnummer niet correct",
    EmptyErrorText: "Alle velden zijn verplicht!",
    ready: "KLAAR!",
    money: "PUSH TO EARN MONEY!",
    workButton: "HOE WERKT HET?",
    myProfile: "Mijn profiel",
    cardDetails: "Bankgegevens",
    add: "Voeg je bankgegevens toe ",
    editProfile: "Taal wijzigen",
    BankName: "Naam bank",
    Iban: "IBAN nummer",
    Bic: "BIC nummer",
    bankbutton: "OPSLAAN",
    friends: "Kandidaten",
    status: {
        wc: 'Waiting Contract',
        ar: 'Archived',
        vd: 'Validating',
        pd: 'Pending'
    },
    loginSuccessfull:{
        ls: 'Login Successfull!',
        pg: 'Push To Earn Money Page'
    },
    addFriends: "Je hebt nog geen kandidaten.Voeg een kandidaat toe en verdien al slapend geld!",
    addFriendsButton: "VOEG EEN KANDIDAAT TOE",
    addFriendNew: "Kandidaat Toevoegen",
    addFriendPhoneButton: "ZOEK IN JE TELEFOONBOEK",
    addFriendName: "Voornaam + Naam",
    friend: "kandidaat",
    agree:"Akkoord",
    disagree: "Niet akkoord",
    Name: "Naam",
    pPolicy: "Private Policy",
    pending: "In afwachting",
    wApproval: "Wachtend op goedkeuring",
    onContract: "Onder contract",
    sick: "Ziek",
    rejected: "Afgekeurd",
    Money: "GELD",
    nothing:"Geen records!",
    backOverview : "terug naar overzicht",
    Total: "Total gewerkte uren",
    TotalNext: "Totaal verdiend",
    payed: "betaald",
    partial: "partieel",
    AdjustmentContract: 'Aanpassings Contract',
    Correction: 'Correctie',
    Time:'Tijd',
    NewTime: 'Nieuwe tijd',
    Information: "Informatie",
    Support: "Support",
    faq: "FAQ",
    duplicateMobilePhone: 'Er bestaat al een duplicaat mobiel nummer',
    invalidMobilePhone:'Mobiel nummer niet geldig',
    one: 'JANUARI',
    two: 'FEBRUARI',
    three: 'MAART',
    four: 'APRIL',
    five: 'MEI',
    six: 'JUNI',
    seven: 'JULI',
    eight: 'AUGUSTUS',
    nine: 'SEPTEMBER',
    ten: 'OKTOBER',
    eleven: 'NOVEMBER',
    twelve: 'DECEMBER',
    resend: "opnieuw versturen",

    //Redux Translations
    completeProfile:'Voltooi alstublieft uw profiel',
    signUpText: 'Meld je aan, want je telefoonnummer bestaat niet in onze database'
    },
    
    French: {

    languageText: "FRANÇAIS",
    SignIn: "Se connecter",
    SignOut: "Sign Out",
    SignWith: "ou connectez-vous avec:",
    SignUpWith: "ou S'inscrire met:",
    SButton: "LOGIN",
    Email: "Adresse e-mail",    
    Password: "Mot de passe",    
    forgot: "Mot de passe oublié?",    
    bottomLine: "Vous n'avez pas de compte? Inscrivez-vous",
    here:"ici!",
    SignUp: "S'inscrire",
    forget: "Mot de passe oublié",    
    resetPassword: "RÉINITIALISER",
    saveData: 'enregistrer des données',
    otp: "Entrer OTP",    
    otpMessage: "Nous vous envoyons un email avec un mot de passe unique(OTP).",
    otpMessagecntd:"Veuillez entrer le code ci-dessous",
    otpSent: "OTP envoyé avec succès à votre numéro de mobile",
    otpError:'OTP est incorrect',
    timeleft: "secondes restantes",
    start: "COMMENCEZ!",
    cancel:'Annuler',
    confirm: 'Confirmer',
    contactSupport: "Contactez le support",
    oldPassword: "Ancien mot de passe",    
    newPassword: "Nouveau mot de passe",    
    confirmPassword: "Répéter",    
    changePassword: "Changer",    
    changeLanguage: "Changer de langue",
    profile: "Profil",    
    firstName: "Prénom",    
    lastName: "Nom de famille",    
    Phone: "Numéro de téléphone",
    PushForJob: "PushForJob",
    FNameErrorText: "Erreur dans prénom",
    LNameErrorText: "Erreur dans nom",
    TelephoneNumberError: "Erreur dans numéro téléphone",
    EmptyErrorText: "Tous les champs sont obligatoires!",
    ready: "PRÊT!",    
    money: "PUSH TO EARN MONEY!",    
    workButton: "COMMENT",    
    myProfile: "Mon profil",
    cardDetails: "Coordonnées bancaires",    
    add: "Ajoutez vos coordonnées bancaires ",
    editProfile: "Changer profil",
    BankName: "Nom de la banque",
    Iban: "Numéro IBAN",
    Bic: "Numéro BIC",
    bankbutton: "ENREGISTRER",
    friends: "Candidats",
    agree:"je suis d'accord",
    disagree: "je ne suis pas d'accord",
    addFriends: "Vous n'avez pas encore de candidats. Ajoutez un candidat et gagnez de l'argent!",
    addFriendsButton: "AJOUTEZ",
    addFriendNew: "Ajoutez un candidat",
    addFriendPhoneButton: "RECHERCHER",
    addFriendName: "Prénom + Nom",
    friend: "Candidat",
    status: {
        wc: 'Waiting Contract',
        ar: 'Archived',
        vd: 'Validating',
        pd: 'Pending'
    },
    loginSuccessfull:{
        ls: 'Login Successfull!',
        pg: 'Push To Earn Money Page'
    },
    pPolicy: "Private Policy",
    Name: "Nom",
    pending: "En attendant",
    wApproval: "En attente d'approbation",    
    onContract: "Sur contract",    
    sick: "Malade",
    rejected: "Rejeté",
    Money: "ARGENT",
    nothing:"Pas d'enregistrements!",
    backOverview : "Retour à l'aperçu",
    Total: "Nombre total d'heures travaillées",
    TotalNext: "Totalement gagné",
    payed: "Payé",
    partial: "Partiel",
    AdjustmentContract: "Contrat d'ajustement",
    Correction: 'Correction',
    Time:'Temps',
    NewTime: 'Nouveau temps',
    Information: "Information",
    Support: "Support",
    faq: "QFP",
    duplicateMobilePhone:'Le numéro de téléphone portable en double existe déjà',
    invalidMobilePhone:'Numéro de téléphone non valide',
    one:'JANVIER',
    two:'février',
    three:'MARS',
    four:'AVRIL',
    five:'MAI',
    six:'JUIN',
    seven:'JUILLET',
    eight:'AOUT',
    nine:'SEPTEMBRE',
    ten:'OCTOBRE',
    eleven:'NOVEMBRE',
    twelve:'décembre',
    resend:"renvoyer",

    //Redux Translations
    completeProfile:'Veuillez compléter votre profil',
    signUpText: "Veuillez vous inscrire, car votre numéro de téléphone n'existe pas dans notre base de données."

    }
    
    }

    export default languageSettings;