const languageSettings = {

    English: {
    
    SignIn: "Sign in",
    SignWith: "or sign in with:",
    SButton: "LOGIN",
    Email: "Email address",
    Password: "Password",
    forgot: "Forgot Password?",
    bottomLine: "Don’t have an account? Sign up ",
    here:" here!",
    SignUp: "SIGN UP",
    forget: "Forgot password?",
    resetPassword: "RESET PASSWORD",
    otp: "Enter OTP",
    otpMessage: "We send you an email with a One Time Password. Please enter the code below",    
    timeleft: "seconds left",
    start: "START NOW!",
    support: "Contact support",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    changePassword: "Change password",
    profile: "Profile",
    firstName: "First name",
    lastName: "Last name",  
    Phone: "Phone number",
    ready: "I’M READY!",
    money: "PUSH TO EARN MONEY!",
    workButton: "HOW DOES IT WORK?",
    myProfile: "My profile",
    cardDetails: "Bank account",
    add: "Add your bank account details here",
    editProfile: "Edit profile",
    BankName: "Bank name",
    Iban: "IBAN number",
    Bic: "BIC number",
    bankbutton: "SAVE",
    friends: "Candidates",
    status: {
        wc: 'Waiting Contract',
        ar: 'Archived',
        vd: 'Validating',
        pd: 'Pending'
    },
    loginSuccessfull:{
        ls: 'Login Successfull!',
        pg: 'Push To Earn Money Page'
    },
    addFriends: "You don’t have any candidates yet. Add a friend and earn money while you sleep!",
    addFriendsButton: "ADD CANDIDATE",
    addFriendNew: "Add candidate",
    addFriendPhoneButton: "SEARCH PHONE CONTACT",    
    addFriendName: "First + last name", 
    friend: "Candidate",    
    Name: "Name",   
    pending: "Pending",    
    wApproval: "Waiting approval",    
    onContract: "On Contract",    
    sick: "Sick",    
    rejected: "Rejected",    
    Money: "Money",    
    backOverview : "Back to overview",    
    Total: "Total hours worked",    
    TotalNext: "Total earned",    
    payed: "Payed",    
    Information: "Information",    
    Support: "Support",    
    faq: "FAQ",    
    },
    
    Dutch: {
    
    SignIn: "Log in",
    SignWith: "of log in met:",
    SButton: "INLOGGEN",  
    Email: "Email adres", 
    Password: "Wachtwoord",
    forgot: "Wachtwoord vergeten?",
    bottomLine: "Nog geen profiel? ",
    here:"Hier! inschrijven",
    SignUp: "Inschrijven",
    forget: "Wachtwoord vergeten",
    resetPassword: "RESET WACHTWOORD",
    otp: "OTP ingeven",
    otpMessage: "We hebben jou een email gestuurd met een One Time Password.Voeg hieronder code toe",
    timeleft: "seconden over",
    start: "START NU!",
    support: "Contacteer support",
    oldPassword: "Oud wachtwoord",
    newPassword: "Nieuw wachtwoord",
    confirmPassword: "Herhaal nieuw wachtwoord",
    changePassword: "Wachtwoord wijizigen",
    profile: "Profiel",
    firstName: "Voornaam",
    lastName: "Naam",
    Phone: "Telefoonnummer",
    ready: "KLAAR!",
    money: "PUSH TO EARN MONEY!",
    workButton: "HOE WERKT HET?",
    myProfile: "Mijn profiel",
    cardDetails: "Bankgegevens",
    add: "Voeg je bankgegevens hier toe",
    editProfile: "Taal wijzigen",
    BankName: "Naam bank",
    Iban: "IBAN nummer",
    Bic: "BIC nummer",
    bankbutton: "OPSLAAN",
    friends: "Kandidaten",
    status: {
        wc: 'Waiting Contract',
        ar: 'Archived',
        vd: 'Validating',
        pd: 'Pending'
    },
    loginSuccessfull:{
        ls: 'Login Successfull!',
        pg: 'Push To Earn Money Page'
    },
    addFriends: "Je hebt nog geen kandidaten.Voeg een kandidaat toe en verdien al slapend geld!",
    addFriendsButton: "VOEG EEN KANDIDAAT TOE",
    addFriendNew: "Kandidaat Toevoegen",
    addFriendPhoneButton: "ZOEK IN JE TELEFOONBOEK",
    addFriendName: "Voornaam + Naam",
    friend: "kandidaat",
    Name: "Naam",
    pending: "In afwachting",
    wApproval: "Wachtend op goedkeuring",
    onContract: "Onder contract",
    sick: "Ziek",
    rejected: "Afgekeurd",
    Money: "Geld",
    backOverview : "terug naar overzicht",
    Total: "Total gewerkte uren",
    TotalNext: "Totaal verdiend",
    payed: "betaald",
    Information: "Informatie",
    Support: "Support",
    faq: "FAQ",
    
    },
    
    French: {
    
    SignIn: "Se connecter",    
    SignWith: "ou connectez-vous avec:",    
    SButton: "LOGIN",    
    Email: "Adresse e-mail",    
    Password: "Mot de passe",    
    forgot: "Mot de passe oublié?",    
    bottomLine: "Vous n'avez pas de compte? Inscrivez-vous",
    here:"ici!",
    SignUp: "S'inscrire",    
    forget: "Mot de passe oublié",    
    resetPassword: "RÉINITIALISER LE MOT DE PASSE",    
    otp: "Entrer OTP",    
    otpMessage: "Nous vous envoyons un email avec un mot de passe unique(OTP). Veuillez entrer le code ci-dessous",    
    timeleft: "secondes restantes",    
    start: "COMMENCEZ!",    
    support: "Contact support",    
    oldPassword: "Ancien mot de passe",    
    newPassword: "Nouveau mot de passe",    
    confirmPassword: "Répéter le nouveau mot de passe",    
    changePassword: "Changer le mot de passe",    
    profile: "Profil",    
    firstName: "Prénom",    
    lastName: "Nom de famille",    
    Phone: "Numéro de téléphone",    
    ready: "PRÊT!",    
    money: "PUSH TO EARN MONEY!",    
    workButton: "COMMENT ÇA MARCHE?",    
    myProfile: "Mon profil",    
    cardDetails: "Coordonnées bancaires",    
    add: "Ajoutez vos coordonnées bancaires ici",    
    editProfile: "Changer profil",    
    BankName: "Nom de la banque",
    Iban: "Numéro IBAN",
    Bic: "Numéro BIC",
    bankbutton: "ENREGISTRER",
    friends: "Candidats",
    addFriends: "Vous n'avez pas encore de candidats. Ajoutez un candidat et gagnez de l'argent!",
    addFriendsButton: "AJOUTEZ UN CANDIDAT",
    addFriendNew: "Ajoutez un candidat",
    addFriendPhoneButton: "RECHERCHER DANS LA LISTE DE CONTACTS",
    addFriendName: "Prénom + Nom",
    friend: "Candidat",
    status: {
        wc: 'Waiting Contract',
        ar: 'Archived',
        vd: 'Validating',
        pd: 'Pending'
    },
    loginSuccessfull:{
        ls: 'Login Successfull!',
        pg: 'Push To Earn Money Page'
    },
    Name: "Nom",
    pending: "En attendant",
    wApproval: "En attente d'approbation",    
    onContract: "Sur contract",    
    sick: "Malade",    
    rejected: "Rejeté",    
    Money: "Argent",    
    backOverview : "Retour à l'aperçu",    
    Total: "Nombre total d'heures travaillées",    
    TotalNext: "Totalement gagné",    
    payed: "Payé",    
    Information: "Information",    
    Support: "Support",    
    faq: "QFP",
    
    }
    
    }

    export default languageSettings;